### ISSUE TITLE
Using command line options.

### ISSUE THREAD

**Issue by sschick-prognos** [stpettersens/gulp-codo#3]
How do I add options (specifically I want --cautious) to codo when it's running through gulp?

**Comment by stpettersens** [comment]
~~Cautious option is not currently supported but I can patch it in for the next release.~~

After reading up more on this: I believe this is just the inverse of using closure comments. So you want the `closure: false` option.  E.g.:

``` js
    return gulp.src('*.coffee', {read: false})
    .pipe(codo({
        // Other options omitted here....
        closure: false
    }));
```

Thanks for your feedback. Please let me know if this works for you, @sschick-prognos. Thanks :)

**Comment by stpettersens** [comment]
*Issue reopened*
